baseURL = "https://digitalclouds.dev/"
languageCode = "en"
title = "Salvydas Lukosius"
theme = "github-style"
googleAnalytics = "G-MT10GVL59X"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Salvydas Lukosius"
  description = "Z-Shell Organization"
  github = "z-shell"
#  facebook = ""
  twitter = "zshell_zi"
#  linkedin = "ss-o"
#  instagram = ""
#  tumblr = ""
  email = "z-shell@digitalclouds.dev"
  url = "https://z.digitalclouds.dev"
  keywords = "A Swiss Army Knife for Zsh Unix shell"
  rss = false
  lastmod = true
  userStatusEmoji = ""
  favicon = "images/avatar.png"
  location = "United Kingdom"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = ""
    owner = ""
    admin = ""
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/z-shell"
  [[params.links]]
    title = "Link2"
    href = "https://z.digitalclouds.dev"
    icon = "https://github.com/z-shell.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]