baseURL = "https://z-shell.digitalclouds.dev/"
languageCode = "en"
title = "❮ ZI ❯"
theme = "github-style"
googleAnalytics = "G-MT10GVL59X"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "❮ ZI ❯"
description = "Open-source society passionate about Zsh, privacy-respecting, and decentralized internet."
github = "z-shell"
#  facebook = ""
twitter = "zshell_zi"
#  linkedin = "ss-o"
#  instagram = ""
#  tumblr = ""
email = "z-shell@digitalclouds.dev"
url = "https://z.digitalclouds.dev"
keywords = "A Swiss Army Knife for Zsh Unix shell."
rss = false
lastmod = true
userStatusEmoji = ""
favicon = "images/avatar.png"
location = "United Kingdom"
enableGitalk = true

[params.gitalk]
clientID = "db9f3795bad94803ab16"
clientSecret = "$CLIENT_SECRET"
repo = "https://github.com/z-shell/z-shell.github.io"
owner = "z-shell"
admin = "ss-o"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/z-shell"
[[params.links]]
title = "Link2"
href = "https://z.digitalclouds.dev"
icon = "https://github.com/z-shell.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
