---
name: "🚀 Deploy Call"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: latest
          extended: true
      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Hugo Build
        run: hugo --minify

  deploy:
    name: "🚀 Deploy"
    uses: z-shell/.github/.github/workflows/deploy-call.yml@main
    secrets:
      personal_token: ${{ secrets.GH_PAT }}
    with:
      publish_branch: "gh-pages"
      publish_dir: "public"
      cname: "github.zshell.dev"
